name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 或者你希望触发的分支名，例如：master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的仓库历史，以便 subtree 可以正常工作

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "15226153903@163.com"
          git config --global user.name "Li-jt"
          git subtree push --prefix dist origin gh-pages
